DROP DATABASE IF EXISTS business_db;
CREATE DATABASE business_db;

USE business_db;


CREATE TABLE role (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  department_id BOOLEAN,
  quantity INT NOT NULL
);

CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name INT NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id BOOLEAN,
  manager_id INT NOT NULL
);

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30)
);